version: 2.1
jobs:
  build:
    steps:
      - checkout
      - setup_remote_docker
      - run: |
         echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
         make build-images
      - run:
          name: Save Docker image layer cache
          command: |
            make persist-images
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
          - /caches
  push_images:
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches
      - run: |
          echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
          make load-cached-images
          make push-images

workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - push_images:
          require:
            - build
          branches:
            only: master
      
